{
 "title": "3phase Data",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "AC current Phase 1",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "amp" } },
   "targets": [
    {
     "alias": "AC current Phase 1",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "3PInverterData",
     "query": "SELECT mean(\"IAC_L1\") FROM \"3PInverterData\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "IAC_L1" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "AC current Phase 2",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "amp" } },
   "targets": [
    {
     "alias": "AC current Phase 2",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "3PInverterData",
     "query": "SELECT mean(\"IAC_L2\") FROM \"3PInverterData\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "IAC_L2" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "AC current Phase 3",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "amp" } },
   "targets": [
    {
     "alias": "AC current Phase 3",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "3PInverterData",
     "query": "SELECT mean(\"IAC_L3\") FROM \"3PInverterData\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "IAC_L3" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "AC voltage Phase 1",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "targets": [
    {
     "alias": "AC voltage Phase 1",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "3PInverterData",
     "query": "SELECT mean(\"UAC_L1\") FROM \"3PInverterData\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "UAC_L1" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "AC voltage Phase 2",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "targets": [
    {
     "alias": "AC voltage Phase 2",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "3PInverterData",
     "query": "SELECT mean(\"UAC_L2\") FROM \"3PInverterData\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "UAC_L2" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "AC voltage Phase 3",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "targets": [
    {
     "alias": "AC voltage Phase 3",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "3PInverterData",
     "query": "SELECT mean(\"UAC_L3\") FROM \"3PInverterData\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "UAC_L3" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  }
 ]
}