{
 "title": "Inverter Current Power",
 "time": { "from": "now/d", "to": "now" },
 "panels": [
  {
   "title": "Production summary",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Current AC power",
   "type": "gauge",
   "gridPos": { "h": 12, "w": 8, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "alias": "AC power",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "CommonInverterData",
     "query": "SELECT mean(\"PAC\") FROM \"CommonInverterData\" WHERE $timeFilter GROUP BY time($__interval) fill(none)",
     "select": [
      [
       { "params": [ "PAC" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "DC Voltage PV1",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 5, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "targets": [
    {
     "alias": "DC Voltage PV1",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "CommonInverterData",
     "query": "SELECT mean(\"UDC\") FROM \"CommonInverterData\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "DAY_ENERGY" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "DC Current PV1",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 5, "x": 13, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "amp" } },
   "targets": [
    {
     "alias": "DC Current PV1",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "CommonInverterData",
     "query": "SELECT mean(\"IDC\") FROM \"CommonInverterData\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "PAC" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Total energy ",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "alias": "Total energy",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "CommonInverterData",
     "query": "SELECT integral(\"PAC\") / 3600 FROM \"CommonInverterData\" WHERE  time >= now()-3650d GROUP BY  time(3650d)",
     "select": [
      [
       { "params": [ "TOTAL_ENERGY" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "AC Power Produced 24h",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 21, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "AC Power Produced",
     "groupBy": [
      { "params": [ "1h" ], "type": "time" }
     ],
     "measurement": "CommonInverterData",
     "query": "SELECT integral(\"PAC\") / 3600000 FROM \"CommonInverterData\" WHERE  time >= now()-24h GROUP BY  time(24h)",
     "select": [
      [
       { "params": [ "PAC" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "DC Voltage PV2",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 5, "x": 8, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "targets": [
    {
     "alias": "DC Voltage PV2",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "CommonInverterData",
     "query": "SELECT mean(\"UDC_2\") FROM \"CommonInverterData\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "DAY_ENERGY" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "DC Current PV2",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 5, "x": 13, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "amp" } },
   "targets": [
    {
     "alias": "DC Current PV2",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "CommonInverterData",
     "query": "SELECT mean(\"IDC_2\") FROM \"CommonInverterData\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "PAC" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 18, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "voltamp" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "alias": "AC Power Absolute",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "CommonInverterData",
     "query": "SELECT mean(\"SAC\") FROM \"CommonInverterData\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "DAY_ENERGY" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 3, "x": 21, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "targets": [
    {
     "alias": "AC Power Absolute",
     "groupBy": [
      { "params": [ "1h" ], "type": "time" }
     ],
     "measurement": "CommonInverterData",
     "query": "SELECT sum(\"PAC\")*20/3600 FROM \"CommonInverterData\" WHERE $timeFilter GROUP BY time(1h)",
     "select": [
      [
       { "params": [ "PAC" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "AC power",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "alias": "AC power",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "CommonInverterData",
     "query": "SELECT mean(\"PAC\") FROM \"CommonInverterData\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "PAC" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "AC Load",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "alias": "AC Load",
     "groupBy": [
      { "params": [ "15m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "CommonInverterData",
     "query": "SELECT mean(\"TOTAL_ENERGY\") FROM \"CommonInverterData\" WHERE $timeFilter GROUP BY time(1h) fill(0)",
     "select": [
      [
       { "params": [ "SAC" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Financial",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Money made in total",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "currencyPLN" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "alias": "Money made in total",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "CommonInverterData",
     "query": "SELECT (integral(\"PAC\") / 3600)*0.00059 FROM \"CommonInverterData\" WHERE  time >= now()-3650d GROUP BY  time(3650d)",
     "select": [
      [
       { "params": [ "TOTAL_ENERGY" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "*0.00059" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Remaining to repay",
   "type": "bargauge",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "currencyPLN" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "alias": "Made made in total",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "CommonInverterData",
     "query": "SELECT (integral(\"PAC\") / 3600)*-0.00059+48700 FROM \"CommonInverterData\" WHERE  time >= now()-3650d GROUP BY  time(3650d)",
     "select": [
      [
       { "params": [ "TOTAL_ENERGY" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "*-0.00059+30500" ], "type": "math" }
      ]
     ]
    }
   ]
  }
 ]
}